# language target
language: cpp
compiler: gcc

# main build matrix
matrix:
  include:
    - name: "Ubuntu Linux"
      os: linux
      dist: xenial
      sudo: required
      env: TARGETOS=linux

# install, install QT5.12.3 from ppa
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
  - sudo apt update
  - sudo apt install build-essential g++ make ffmpeg sox mplayer libnotify-dev mesa-common-dev libglvnd-dev
  - sudo apt install qt-latest
  - echo "/opt/qt510/bin" | sudo tee /etc/xdg/qtchooser/default.conf
  - echo "/opt/qt510/lib" | sudo tee -a /etc/xdg/qtchooser/default.conf
  - qtchooser -print-env
  - qmake -v

# build & test scripts
script:
  - qmake mystiq.pro
  - make
  - sudo make install

# notifications (only via telegram)
notifications:
  email: true
  #webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# no deploy section for now.
